#!/bin/bash

#usage: script APfile PAfile outputfolder output-filename-base

# Now for version 0.5.7


__conda_setup="$('/proj/NIRAL/tools/Anaconda/Anaconda_NIRAL/bin/conda' 'shell.bash' 'ho
ok' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/proj/NIRAL/tools/Anaconda/Anaconda_NIRAL/etc/profile.d/conda.sh" ]; then
        . "/proj/NIRAL/tools/Anaconda/Anaconda_NIRAL/etc/profile.d/conda.sh"
    else
        export PATH="/proj/NIRAL/tools/Anaconda/Anaconda_NIRAL/bin:$PATH"
    fi
fi
unset __conda_setup

conda activate dmriplayground_0.5.7


#module add fsl/6.0.6
module remove qt
module remove python

echo sbatch -p general -N 1 -n 7 --mem 60g -t 80:00:00 --wrap="dmriprep run  -i $1 $2 -o $3 -p /proj/NIRAL/studies/IBIS/EP/processing/dMRI/protocol_dmriprep_all_0.5.7.yml -f NRRD --num-threads 6 --output-file-base $4"

sbatch -p general -N 1 -n 7  --mem 60g -t 80:00:00 --wrap="dmriprep run -i $1 $2 -o $3 -p /proj/NIRAL/studies/IBIS/EP/processing/dMRI/protocol_dmriprep_all_0.5.7.yml -f NRRD --num-threads 6 --output-file-base $4"

exit

