#!/bin/bash

# usage: ... /inputpath/input.nrrd /outputFolder output.nii.gz

# version 0.5.7

__conda_setup="$('/proj/NIRAL/tools/Anaconda/Anaconda_NIRAL/bin/conda' 'shell.bash' 'ho
ok' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/proj/NIRAL/tools/Anaconda/Anaconda_NIRAL/etc/profile.d/conda.sh" ]; then
        . "/proj/NIRAL/tools/Anaconda/Anaconda_NIRAL/etc/profile.d/conda.sh"
    else
        export PATH="/proj/NIRAL/tools/Anaconda/Anaconda_NIRAL/bin:$PATH"
    fi
fi
unset __conda_setup

conda activate dmriplayground_latest
#conda activate dmriplayground_0.5.7

#module add fsl/6.0.6
module remove qt
module remove python


echo dmriprep run  -i $1 -o $2 -p /proj/NIRAL/studies/IBIS/EP/processing/dMRI/protocol_dmriprepConvert.0.5.7.yml -f NIFTI --num-threads 1 --output-file-base $3

dmriprep run  -i $1 -o $2 -p /proj/NIRAL/studies/IBIS/EP/processing/dMRI/protocol_dmriprepConvert.0.5.7.yml -f NIFTI --num-threads 1 --output-file-base $3

exit

